### ISSUE TITLE
Added relation is not deleted on rollback 

### ISSUE THREAD

**Issue by armen9494** [Neurony/laravel-revisions#11]
Have tried on relationship "hasMany"

**Comment by zbiller** [comment]
Hi @armen9494 

Can you please be more specific in what the issue is here, because I'm afraid I don't quite fully understand.

Thanks! :)

**Comment by armen9494** [comment]
I have Models -  "Article" and "Questions". Article hasMany Questions.
My steps
1. Running saveAsRevision() on Article (revision is created).
2. Adding one more question.
3. Rolling back to revision created on step 1.

Problem - Added question on step 2 is not deleted.

**Comment by zbiller** [comment]
Hi @armen9494 

I would look into this as soon as I find a little free time.

**Comment by zbiller** [comment]
Hey @armen9494 

Sorry for the long wait.
This issue is now solved in version `3.1.0`.

Thanks again for spotting this :)

**Comment by mrgodhani** [comment]
@zbiller Does this fix also apply for Laravel 5.7 release version?
