### ISSUE TITLE
Comparing idea

### ISSUE THREAD

**Issue by armen9494** [Neurony/laravel-revisions#14]
Great package, I think it will be useful to have comparing feature.
So if I will get Model without saving it into DB, I can compare it in front-end and after, if I want, restore that version id DB.
As I see, it can be easy implemented doing this steps
1. Copy RollbackRevisionJsonRepresentation.php and remove save() and attach() methods.
2. In HasRevisions trait copy rollbackToRevision() method and 
    2.1. Delete "$this>saveAsRevision();" line.
    2.2. Replace rollbackModelToRevision(), rollbackDirectRelationToRevision(), rollbackPivotedRelationToRevision() with methods created in new Trait (created in step 1).
Maybe there are some steps too, as I don't know whole construction.
Thanks!

**Comment by zbiller** [comment]
Hi @armen9494 

I don't think implementing a comparing feature will be withing the scope of this package, which are revisions.

I think it will be better to have the package doing one specific thing.

Also, there are already open-source packages for comparing sets of data.

Thanks :)

**Comment by armen9494** [comment]
Maybe I have not described right.
How is real life logic - for example, you store multiple revisions of article. Now user wants to rollback to one of them. But before rolling back he needs to check which one he wants. How can he check? You cannot present him json, it will be converted to model for presenting it.

**Comment by zbiller** [comment]
@armen9494 

You can do that right now:

1. In your controller method that returns the view for displaying the revision

```php
DB::beginTransaction();

$revision = Revision::find($id);
$model = $revision->revisionable;

$model->rollbackToRevision($revision);

// don't commit the transaction

return view()->with([
    'model' => $model,
    'revision' => $revision,
]);
```

At this point, your `$model` is an instance of your actual model class containing the data from the revision.

2. At the end of your displaying (in the bottom of your view) (optional)

```php
DB::rollBack();
```

**Comment by armen9494** [comment]
Good idea, but I think it will add additional queries to DB. I think, will be better to construct it on "empty" model, as we have all info in metadata.
