### ISSUE TITLE
Specify different Relationship Classes

### ISSUE THREAD

**Issue by mstaack** [Neurony/laravel-revisions#22]
Currently i am using this package together with:
https://github.com/staudenmeir/eloquent-json-relations/tree/master/src/Relations/Postgres

The default setup does not work for relationships b/c of different Classnames in `RelationHelper`
Adding the specific one like:
```
    /**
     * All available Laravel's direct relations.
     *
     * @var array
     */
    protected static $directRelations = [
        HasOne::class,
        \Staudenmeir\EloquentJsonRelations\Relations\Postgres\HasOne::class,
        MorphOne::class,
        HasMany::class,
        MorphMany::class,
        BelongsTo::class,
        MorphTo::class,
    ];
``` 
basically solves the problem, but editing vendor classes of course does not really work ;)

how about adding these via config entry maybe?

Cheers & Thanks for this great package.

**Comment by mstaack** [comment]
`instanceof` might also work...

**Comment by zbiller** [comment]
Hi @mstaack 

Adding them via a config entry sounds like a good idea. I'll happily accept a PR with this.

However, meanwhile, you could extend the `HasRevisions` trait and use your own `RelationHelper` class.
