### ISSUE TITLE
Error rolling back to revision without related records

### ISSUE THREAD

**Issue by acontia** [Neurony/laravel-revisions#26]
I have two models: Post and Media.
Post has a relation MorphMany with Media.

1) I create a post without any media record associated to it and save it
2) I add a media to a post and save it
3) I rollback to the revision created in 1), which didn't have Media items, and I got a fatal error in `RollbackRevisionJsonRepresentation::rollbackDirectRelationToRevision`.

Looks like `$relatedPrimaryKey` is empty at that point, and it is used to perform the query
``` $oldRelated = $this->{$relation}()->pluck($relatedPrimaryKey)->toArray();```
, which fails.

With the provided patch it seems to work fine, although I haven't ran any tests and I don't know if it has any side effects.

Any thoughts?

[rollback-to-revision-without-related-records.patch.txt](https://github.com/Neurony/laravel-revisions/files/4771712/rollback-to-revision-without-related-records.patch.txt)

**Comment by acontia** [comment]
Seems related to the fix committed here: https://github.com/Neurony/laravel-revisions/issues/11

**Comment by zbiller** [comment]
Hi @acontia    

Unfortunately this package is now discontinued. 
Please check out [Varbox](https://varbox.io) (Laravel Admin Panel) for this functionality, but much more.

- documentation: [https://varbox.io/docs](https://varbox.io/docs)
- live demo: [https://demo.varbox.test/admin](https://demo.varbox.test/admin)
- repository: [https://github.com/VarboxInternational/varbox](https://github.com/VarboxInternational/varbox)

Thank you!

**Comment by acontia** [comment]
Well, that cost 299€.
Any idea what is the best free alternative?
Thanks
