### ISSUE TITLE
Laravel 8 support

### ISSUE THREAD

**Issue by StygianTraveler** [Neurony/laravel-revisions#27]
Laravel 8 is out. Please update your composer.json to support it. Thanks.

**Comment by zbiller** [comment]
Hi @StygianTraveler  

Unfortunately this package is now discontinued. 
Please check out [Varbox](https://varbox.io) (Laravel Admin Panel) for this functionality, but much more.

- documentation: [https://varbox.io/docs](https://varbox.io/docs)
- live demo: [https://demo.varbox.test/admin](https://demo.varbox.test/admin)
- repository: [https://github.com/VarboxInternational/varbox](https://github.com/VarboxInternational/varbox)

Thank you!
