### ISSUE TITLE
Not on packagist?

### ISSUE THREAD

**Issue by JayBizzle** [Neurony/laravel-revisions#3]
Hi,

I was interested to try this package out, but it seems you haven't published to Packagist yet?

Hope to try it soon.

Thanks 👍

**Comment by zbiller** [comment]
Hi @JayBizzle 

Sorry for the delay!
The package is now available on Packagist: `composer require zbiller/laravel-revisions`.

Thanks! :)

**Comment by JayBizzle** [comment]
👍
