### ISSUE TITLE
Support on Laravel v5.5.44

### ISSUE THREAD

**Issue by superern** [Neurony/laravel-revisions#4]
I'm using 5.5.44 and cannot install the package.

**Comment by zbiller** [comment]
Hi @superern 

This package is compatible with Laravel >=5.7

**Comment by superern** [comment]
is there any plans to have >=5.4 compatibility in future versions?

Thanks for replying. this is really a good package.

**Comment by zbiller** [comment]
I will try making it compatible with >= 5.5 when I find a little time available.

Theoretically this should work as this package was born from a Laravel 5.5 project, but I guess I will have to re-write some bits.

Thanks for your support! :)

**Comment by superern** [comment]
sounds awesome!. looking forward for it.
